kind: Service
apiVersion: v1
metadata:
  name: argo-ui-custom
  namespace: argo
spec:
  selector:
    app: argo-ui
  type: NodePort
  ports:
  - port: 80
    targetPort: 9001


# Delete the default argo-ui service, create above service. Get service ip -- `kubectl get svc -n argo`
# Access <minikube-ip>:<service-port>